version: "3.3"
services:
  dam-reservas-y-favoritos-database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password # Para que no nos obligue a resetear la pass
    restart: always
    environment:
      MYSQL_DATABASE: "reservasyfavoritos"
      MYSQL_ROOT_PASSWORD: "ACA VA UNA CLAVE RE SEGURA QUE NI LOCO COMMITEO"
    ports:
      - "3306:3306"
    volumes:
      - ~/db:/var/lib/mysql