version: "3.3"
services:
  dam-reservas-y-favoritos-api:
    image: dam-reservas-favoritos-ktor:latest
    restart: always
    depends_on:
      - dam-reservas-y-favoritos-database
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      DBHOST: "dam-reservas-y-favoritos-database"
      DBPORT: "3306"
      DBNAME: "DEFAULT_DB_NAME"
      DBPASS: "DEFAULT_DB_PASS"
      VIRTUAL_HOST: "dam-recordatorio-favoritos-api.duckdns.org"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "dam-recordatorio-favoritos-api.duckdns.org"
      LETSENCRYPT_EMAIL: "leandroamarillo95@gmail.com"

  dam-reservas-y-favoritos-database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password # Para que no nos obligue a resetear la pass
    restart: always
    environment:
      MYSQL_DATABASE: "DEFAULT_DB_NAME"
      MYSQL_ROOT_PASSWORD: "DEFAULT_DB_PASS"
    ports:
      - "3306:3306"
    volumes:
      - ~/db:/var/lib/mysql

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    depends_on:
      - dam-reservas-y-favoritos-api

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: "leandroamarillo95@gmail.com"

volumes:
  certs:
  html:
  vhostd:
  confd: